"""RocketLauncher system INI and HyperSpin Main Menu XML generation."""
from __future__ import annotations

import xml.etree.ElementTree as ET
from datetime import datetime
from pathlib import Path
from typing import Optional

from ._compat import et_indent
from .config import Config, get_rom_extensions, get_system_overrides
from .database import _set_text as _set
from .mainmenu import _main_menu_path


EMULATOR_MAP: dict[str, str] = {
    "mame": "MAME",
    "arcade": "MAME",
    "cps1": "MAME",
    "cps2": "MAME",
    "cps3": "MAME",
    "neogeo": "MAME",
    "neo geo": "MAME",
    "nes": "RetroArch",
    "nintendo entertainment system": "RetroArch",
    "famicom": "RetroArch",
    "snes": "RetroArch",
    "super nintendo": "RetroArch",
    "super famicom": "RetroArch",
    "genesis": "RetroArch",
    "mega drive": "RetroArch",
    "sega genesis": "RetroArch",
    "n64": "Project64",
    "nintendo 64": "Project64",
    "gba": "RetroArch",
    "game boy advance": "RetroArch",
    "gameboy": "RetroArch",
    "game boy": "RetroArch",
    "game boy color": "RetroArch",
    "gbc": "RetroArch",
    "psx": "RetroArch",
    "playstation": "RetroArch",
    "ps2": "PCSX2",
    "playstation 2": "PCSX2",
    "dreamcast": "Demul",
    "gamecube": "Dolphin",
    "wii": "Dolphin",
    "atari 2600": "RetroArch",
    "atari 7800": "RetroArch",
    "atari lynx": "RetroArch",
    "master system": "RetroArch",
    "sega master system": "RetroArch",
    "game gear": "RetroArch",
    "turbografx": "RetroArch",
    "turbografx-16": "RetroArch",
    "pc engine": "RetroArch",
    # PC / Windows / Steam — RocketLauncher PCLauncher module reads a
    # per-game INI to find the actual executable.
    "pc": "PCLauncher",
    "pc games": "PCLauncher",
    "windows": "PCLauncher",
    "windows games": "PCLauncher",
    "steam": "PCLauncher",
    "steam games": "PCLauncher",
}


def guess_emulator(system_name: str) -> str:
    ovr = get_system_overrides().get(system_name, {})
    if isinstance(ovr.get("emulator"), str) and ovr["emulator"]:
        return ovr["emulator"]
    return EMULATOR_MAP.get(system_name.lower(), "RetroArch")


# Default executable names per emulator — used when generating
# Global Emulators.ini.  Users can edit the file afterwards; spindoctor
# refuses to overwrite an existing file unless --overwrite-global is set.
EMULATOR_EXECUTABLES: dict[str, str] = {
    "MAME": "mame.exe",
    "RetroArch": "retroarch.exe",
    "Project64": "Project64.exe",
    "PCSX2": "pcsx2.exe",
    "Dolphin": "Dolphin.exe",
    "Demul": "demul.exe",
    "PCLauncher": "PCLauncher.exe",
}

EMULATOR_EXTENSIONS: dict[str, str] = {
    "MAME": "zip|7z",
    "RetroArch": "zip|7z|nes|sfc|smc|md|bin|gba|gb|gbc|n64|z64",
    "Project64": "z64|n64|v64|zip",
    "PCSX2": "iso|bin|img",
    "Dolphin": "iso|gcm|wbfs|rvz",
    "Demul": "chd|cdi|gdi|cue",
    "PCLauncher": "exe|lnk|url|bat",
}


# ─── Global Emulators.ini ─────────────────────────────────────────────────────

def generate_global_emulators_ini(
    config: Config,
    output_base: Optional[Path] = None,
    overwrite: bool = False,
) -> tuple[Optional[Path], str]:
    """Generate ``RocketLauncher/Settings/Global Emulators.ini``.

    Returns ``(path, status)`` where status is one of
    ``"created"``, ``"skipped-exists"``, ``"overwritten"``.

    By default does not overwrite an existing file (RL UI / users may have
    customised it).  Pass ``overwrite=True`` to replace it.
    """
    rl_base = output_base or (
        Path(config.rocketlauncher_dir) if config.rocketlauncher_dir else None
    )
    if not rl_base:
        raise ValueError(
            "rocketlauncher_dir not configured. "
            "Run: spindoctor config set rocketlauncher_dir <path>  "
            "or pass --output-dir."
        )

    settings_dir = rl_base / "Settings"
    settings_dir.mkdir(parents=True, exist_ok=True)
    ini_path = settings_dir / "Global Emulators.ini"

    if ini_path.exists() and not overwrite:
        return ini_path, "skipped-exists"

    # Distinct emulators referenced by EMULATOR_MAP
    emulators = sorted(set(EMULATOR_MAP.values()))
    emulators_root = (
        Path(config.emulators_dir) if config.emulators_dir else Path("Emulators")
    )

    lines: list[str] = [
        "; Generated by SpinDoctor.",
        "; Edit paths here once; per-system Settings/<System>.ini will reference",
        "; these emulators by name (RocketLauncher hierarchy).",
        "",
    ]
    for emu in emulators:
        exe = EMULATOR_EXECUTABLES.get(emu, f"{emu}.exe")
        ext = EMULATOR_EXTENSIONS.get(emu, "zip|7z")
        emu_dir = emulators_root / emu
        lines.extend([
            f"[{emu}]",
            f"Emulator_Path={emu_dir}",
            f"Emulator_Application_Path={emu_dir / exe}",
            f"Emulator_Extension={ext}",
            "",
        ])

    status = "overwritten" if ini_path.exists() else "created"
    ini_path.write_text("\n".join(lines), encoding="utf-8")
    return ini_path, status


# ─── RocketLauncher INI ───────────────────────────────────────────────────────

def generate_rl_system_ini(
    system_name: str,
    config: Config,
    output_base: Optional[Path] = None,
) -> Path:
    """Write a RocketLauncher per-system settings INI file.

    File goes to: <rl_dir|output_base>/Settings/<SystemName>.ini
    """
    rl_base = output_base or (Path(config.rocketlauncher_dir) if config.rocketlauncher_dir else None)
    if not rl_base:
        raise ValueError(
            "rocketlauncher_dir not configured. "
            "Run: spindoctor config set rocketlauncher_dir <path>  "
            "or pass --output-dir."
        )

    settings_dir = rl_base / "Settings"
    settings_dir.mkdir(parents=True, exist_ok=True)
    ini_path = settings_dir / f"{system_name}.ini"

    rom_path = str(Path(config.roms_dir) / system_name)
    emulator = guess_emulator(system_name)
    extensions = "|".join(ext.lstrip(".") for ext in get_rom_extensions(system_name))

    lines = [
        "[Settings]",
        f"Default_Emulator={emulator}",
        f"Rom_Path={rom_path}",
        f"Rom_Extension={extensions}",
        "",
        f"[{emulator}]",
        f"Rom_Path={rom_path}",
        "",
    ]
    ini_path.write_text("\n".join(lines), encoding="utf-8")
    return ini_path


def generate_synthetic_system_ini(system_name: str, rocketlauncher_dir: Path) -> Path:
    """Write a minimal RocketLauncher system INI for a synthetic PCLauncher wheel.

    Synthetic systems (Favorites, Recently Played, Most Played) store per-game
    INIs under Modules/PCLauncher/<system>/ — so that directory is the
    Rom_Path, and the extension is "ini".  Without this file RocketLauncher
    can't route launch requests for the system and throws "Cannot find
    <system>.ini".
    """
    settings_dir = rocketlauncher_dir / "Settings"
    settings_dir.mkdir(parents=True, exist_ok=True)
    ini_path = settings_dir / f"{system_name}.ini"
    pclauncher_dir = rocketlauncher_dir / "Modules" / "PCLauncher" / system_name
    lines = [
        "[Settings]",
        "Default_Emulator=PCLauncher",
        f"Rom_Path={pclauncher_dir}",
        "Rom_Extension=ini",
        "",
        "[PCLauncher]",
        f"Rom_Path={pclauncher_dir}",
        "",
    ]
    ini_path.write_text("\n".join(lines), encoding="utf-8")
    return ini_path


# ─── HyperSpin Main Menu XML ──────────────────────────────────────────────────

def _read_main_menu_systems(path: Path) -> list[str]:
    """Return current <game name="..."/> entries from Main Menu.xml (or [])."""
    if not path.exists():
        return []
    try:
        tree = ET.parse(path)
    except ET.ParseError as exc:
        import sys
        print(
            f"WARNING: Main Menu.xml at {path} could not be parsed ({exc}) — "
            "existing system entries will not be preserved. "
            "Run: spindoctor doctor  to check your HyperSpin files.",
            file=sys.stderr,
        )
        return []
    return [
        (g.get("name") or "").strip()
        for g in tree.getroot().findall("game")
        if (g.get("name") or "").strip()
    ]


def _write_main_menu(systems: list[str], out_path: Path) -> Path:
    """Write Main Menu.xml in HyperSpin's native minimal format.

    Native shape: a bare ``<menu>`` containing ``<game name="..."/>`` entries,
    no XML declaration, no ``<header>``, no child elements. This is what
    HyperSpin ships and what its parser expects; bloated formats (with empty
    ``<description>``/``<enabled>`` children) cause "Error creating main menu"
    on some HyperSpin builds.
    """
    out_path.parent.mkdir(parents=True, exist_ok=True)
    root = ET.Element("menu")
    for sys_name in systems:
        ET.SubElement(root, "game", name=sys_name)

    tree = ET.ElementTree(root)
    et_indent(tree)
    with open(out_path, "wb") as f:
        tree.write(f, encoding="utf-8", xml_declaration=False)
    return out_path


def generate_hs_main_menu(
    systems: list[str],
    config: Config,
    output_base: Optional[Path] = None,
) -> Path:
    """Sync Databases/Main Menu/Main Menu.xml to match *systems*.

    Preserves the existing wheel order when the file already exists:
    - entries still present in *systems* keep their current positions
    - newly-discovered systems are appended at the end (in the order
      they appear in *systems*, which is typically alphabetical)
    - entries no longer in *systems* are dropped

    When the file doesn't exist yet the order of *systems* is used as-is.
    """
    target = _main_menu_path(config, output_base)
    systems_set = set(systems)

    existing = _read_main_menu_systems(target)
    ordered: list[str] = [s for s in existing if s in systems_set]
    already_listed = set(ordered)
    for s in systems:
        if s not in already_listed:
            ordered.append(s)

    return _write_main_menu(ordered, target)


def upsert_main_menu_system(
    system_name: str,
    config: Config,
    output_base: Optional[Path] = None,
) -> tuple[Path, bool]:
    """Add *system_name* to Main Menu.xml without disturbing other entries.

    Returns ``(path, added)`` where ``added`` is False if the system was
    already listed.
    """
    out_path = _main_menu_path(config, output_base)
    existing = _read_main_menu_systems(out_path)
    if system_name in existing:
        return out_path, False
    existing.append(system_name)
    _write_main_menu(existing, out_path)
    return out_path, True


# ─── System database stubs ────────────────────────────────────────────────────

def generate_system_db_stubs(
    systems: list[str],
    config: Config,
    output_base: Optional[Path] = None,
) -> list[Path]:
    """Create empty database XMLs for systems that don't have one yet."""
    from .database import HyperspinDatabase

    created = []
    db_base = output_base / "Databases" if output_base else config.databases_dir

    for sys_name in systems:
        xml_path = db_base / sys_name / f"{sys_name}.xml"
        if xml_path.exists():
            continue
        xml_path.parent.mkdir(parents=True, exist_ok=True)
        db = HyperspinDatabase(sys_name, xml_path)
        db.load()
        db.save(backup=False)
        created.append(xml_path)

    return created


# ─── PCLauncher per-game INIs ─────────────────────────────────────────────────

def _pclauncher_ini_text(executable) -> str:
    """Render the PCLauncher INI body that points at *executable*.

    *executable* may be any path-like (str, Path, PureWindowsPath).  We
    leave the path string verbatim so Windows-style paths produced from a
    macOS/Linux dev box (or vice-versa) round-trip without mangling.
    """
    return (
        "[Settings]\n"
        f"ApplicationPath={executable}\n"
        "ApplicationParameters=\n"
        f"StartIn={executable.parent}\n"
    )


def pclauncher_exe_info_text(
    applicationpath, parameters: str = "", rompath: str = "",
) -> str:
    """Render an `[exe info]`-style PCLauncher INI body.

    PCLauncher accepts two INI dialects: the standard `[Settings]` form
    (see `_pclauncher_ini_text`) and `[exe info]`, which is what the
    favorites/recent/most-played helpers use when they need PCLauncher
    to invoke RLaunch (delegating through to the real emulator) or a
    plain .bat. Single source of truth for both call sites.
    """
    return (
        "[exe info]\n"
        f"applicationpath={applicationpath}\n"
        f"rompath={rompath}\n"
        f"parameters={parameters}\n"
    )


def generate_pclauncher_inis(
    system_name: str,
    title_to_path: dict,
    config: Config,
    output_base: Optional[Path] = None,
    overwrite: bool = False,
) -> tuple[Path, list[Path], list[Path]]:
    """Write per-game PCLauncher INIs for *system_name*.

    Each INI lives at
    ``<RL>/Modules/PCLauncher/<system>/<title>.ini`` and tells the
    PCLauncher AHK module which executable to actually launch when
    HyperSpin asks RocketLauncher to run *<title>*.

    Returns ``(module_dir, written_paths, skipped_paths)``.  Existing INIs
    are left alone unless *overwrite* is set so user edits survive a
    re-run of ``add-pc-system``.
    """
    rl_base = output_base or (
        Path(config.rocketlauncher_dir) if config.rocketlauncher_dir else None
    )
    if not rl_base:
        raise ValueError(
            "rocketlauncher_dir not configured. "
            "Run: spindoctor config set rocketlauncher_dir <path>  "
            "or pass --output-dir."
        )

    module_dir = rl_base / "Modules" / "PCLauncher" / system_name
    module_dir.mkdir(parents=True, exist_ok=True)

    written: list[Path] = []
    skipped: list[Path] = []
    for title, exe_path in sorted(title_to_path.items()):
        ini_path = module_dir / f"{title}.ini"
        if ini_path.exists() and not overwrite:
            skipped.append(ini_path)
            continue
        ini_path.write_text(_pclauncher_ini_text(exe_path), encoding="utf-8")
        written.append(ini_path)
    return module_dir, written, skipped


